name: Java-CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: my-step
        run: ci/build-app.sh
  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    - name: Test
        run: ci/unit-test-app.sh
  Artifact:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .